workflows:
  android-release:
    name: Android Release
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17
    scripts:
      - name: Set up Flutter environment
        script: | 
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      # Si quieres subirla a Play Store, necesitarías más configuración aquí.
      # Por ahora, solo lo dejamos vacío.
